name: push

on:
  push:
    branches: [main]

jobs:
  lint-format-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: ğŸ° Install Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      - name: ğŸ‡ Install Dependencies using Bun
        run: bun install
      - name: ğŸ§¹ Lint
        run: bun lint
      - name: ğŸ§¹ Lint & Format (Biome)
        run: bun check:fix
      # TODO: currently not passing for Elysia Eden issue
      # - name: âš™ï¸ Check types
      #   run: bun typecheck:tsc
      # - name: ğŸš§ Build
      #   run: bun run build
      # - name: ğŸ§ª Test
      #   run: bun run test